[[keymaps]]
command = "open_folder"
key = "Alt+o"

[[keymaps]]
command = "close_folder"
key = "Alt+q"

[[keymaps]]
command = "duplicate_line_down"
mode = "i"
key = "Alt+d"

[[keymaps]]
command = "indent_line"
key = "Alt+]"

[[keymaps]]
command = "select_current_line"
mode = "i"
key = "Alt+l"

[[keymaps]]
command = "insert_cursor_above"
mode = "i"
key = "Ctrl+Alt+ArrowUp"